layout_spectrum: 0
color:
  saturation: 0.6505376
  lightness: 0.7165391
  brandStrength: 0.9283154
  brandColors:
    - '#171717'
    - '#30BFCD'
    - '#FFFFFF'
    - '#CECECE'
    - '#5C5C5C'
  rhythmicContrast: 0.4283154
typography_spectrum: 0.4390681
name: KreativeDesigns
